import fs from "node:fs/promises";
import { getMetadataPath } from "./paths";

export type SearchDoc = {
  kind: "notes" | "gallery";
  slug: string;
  title: string;
  summary: string;
  tags: string[];
  text: string;
};

// Generated by tools/site-builder; contains the stripped full text of every
// published document for client-side search.
export async function loadSearchIndex(): Promise<SearchDoc[]> {
  const source = await fs.readFile(getMetadataPath("search"), "utf8");
  const parsed = JSON.parse(source);
  return Array.isArray(parsed) ? parsed : [];
}
